"""empty message

Revision ID: 3309977f4197
Revises: 8599bcf5ca4d
Create Date: 2024-03-05 23:19:55.706650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3309977f4197'
down_revision: Union[str, None] = '8599bcf5ca4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('test', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'test')
    # ### end Alembic commands ###
